### ISSUE TITLE
no functionality for sharing image of the meme

### ISSUE THREAD

**Issue by rahulsain3000** [rahulsain3000/MemeIt#1]
If anyone could help me updating the code to share image rather than url of meme, They are most welcome.

Please read contributing.md first for forking this repo.

**Comment by thunder-coding** [comment]
First Upload the screenshot of your memes in your repository.

Then in your README.md file add this
<img src="https://github.com/your-username/repository-name/blob/master/image-location/image-name-with-file-extension">

**Comment by rahulsain3000** [comment]
no, My problem is that there is share button in this app and I have put a functionality that share url of that meme that is being fetched from open API.

But i want to change this functionality to share image(*.jpeg/*.png) file to apps like whatsapp Instagram etc

**Comment by thunder-coding** [comment]
Sorry, But I don't have any idea of Kotlin.

I found this on the web.
Try this : https://developer.android.com/training/secure-file-sharing/share-file

**Comment by erwinkaaa** [comment]
Hi, i would like to contribute to this! Can u assign it to me? :-)

**Comment by erwinkaaa** [comment]
Hi! I am new to open source.
I can submit the pull request during Hacktoberfest. Can you assign this to me so that I can make changes and submit the PR! Also please suggest any further improvements if needed.
Thank you!

**Comment by rahulsain3000** [comment]
@erwinkaaa can you add a feature of sharing .png of the image through whatsapp facebook etc?

**Comment by erwinkaaa** [comment]
Sure! But is it okay if i do the PR during hacktoberfest?

**Comment by rahulsain3000** [comment]
yes sure no problem but it should add this desired feature that i have marked and additional ui improvemnt is most welcome

**Comment by erwinkaaa** [comment]
I did the PR!
